### ISSUE TITLE
Do your first on-call shift

### ISSUE THREAD

**Issue by seanh** [hypothesis/onboarding#73]
You're now ready to do your first shift as the primary on-call engineer: being first responder to any incidents that happen and attempting to diagnose and mitigate the problem or escalating it to other team members.

All engineers at Hypothesis do their share of on-call shifts. As engineers we're most familiar with the code and can troubleshoot issues quickest. We're also the ones empowered to make the service more robust: building better software that is less likely to fail in production.

- [x] **Buddy**: add the new engineer to the on-call schedules in PagerDuty.
- [x] **Engineer**: read our [on-call handbook](https://github.com/hypothesis/playbook/blob/main/docs/oncall-handbook.md) before your first on-call shift starts. It documents your on-call responsibilities, our monitoring systems, and our incident response procedures.
- [x] **Engineer**: check off this item once your first primary on-call shift has ended.

**Comment by acelaya** [comment]
On call duty in progress, so closing this.
