### ISSUE TITLE
Update skyliner links in the docs

### ISSUE THREAD

**Issue by mtomilov** [hypothesis/onboarding#90]
Unfortunately skyliner domain seems to have been discontinued.
Luckily they moved the articles of interest to their medium blog.

# merging

https://blog.skyliner.io/ship-small-diffs-741308bec0d1 ->  
https://medium.com/skylinerhq/ship-small-diffs-741308bec0d1
# deploying

https://blog.skyliner.io/you-cant-have-a-rollback-button-83e914f420d9 ->  
https://medium.com/skylinerhq/you-cant-have-a-rollback-button-83e914f420d9

https://blog.skyliner.io/risky-business-requires-active-operators-9debbb082995 ->  
https://medium.com/skylinerhq/risky-business-requires-active-operators-9debbb082995

Do you want me to create a PR for that?

**Comment by robertknight** [comment]
> Do you want me to create a PR for that?

Yes please. The principles in these articles are still very relevant for us, so we should keep these links. It is unfortunate that they are hosted on Medium with all of its upsell banners, but at least the content is there.
